version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: dev
      DB_HOST: postgres # Updated to match the PostgreSQL service name
      DB_PORT: 5432
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: 'dev'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    expose:
      - '5432'
    networks:
      - backend
    volumes:
      - data:/var/lib/postgresql/data # Persist data for PostgreSQL

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
